source_path: "{.*,**/*}"
shared_cache: true
ignored:
  go:
    - github.mpi-internal.com/**/*
allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
reviewed:
  go:
    - golang.org/x/crypto/ed25519
    - golang.org/x/net/bpf
    - golang.org/x/net/internal/iana
    - golang.org/x/net/internal/socket
    - golang.org/x/net/ipv4
    - golang.org/x/net/ipv6
    - golang.org/x/sys/unix
    - github.com/miekg/dns
    - github.com/opencontainers/go-digest
